using Amazon.DynamoDBv2.DataModel;

namespace PropertyHubLibrary.Models
{
    [DynamoDBTable("Property")]
    public class Property
    {
        [DynamoDBHashKey] // Partition Key, official MLS number
        public required string MLS { get; set; }

        // Mandatory fields in regular property listing
        [DynamoDBProperty("Type")]
        public required string Type { get; set; }

        [DynamoDBProperty("Price")]
        public required decimal Price { get; set; }

        [DynamoDBProperty("Bedrooms")]
        public required int Bedrooms { get; set; }

        [DynamoDBProperty("Bathrooms")]
        public required int Bathrooms { get; set; }

        [DynamoDBProperty("Parkings")]
        public required int Parkings { get; set; }

        [DynamoDBProperty("Size")]
        public required int Size { get; set; }

        [DynamoDBProperty("YearBuilt")]
        public required int YearBuilt { get; set; }

        [DynamoDBProperty("Tax")]
        public required decimal Tax { get; set; }

        [DynamoDBProperty("Address")]
        public required Address Address { get; set; }

        [DynamoDBProperty("Agent")]
        public required Agent Agent { get; set; }

        [DynamoDBProperty("Status")]
        public required string Status { get; set; }

        [DynamoDBProperty("Description")]
        public required string Description { get; set; }

        // Optional fields
        [DynamoDBProperty("ImageUrls")]
        public List<string>? ImageUrls { get; set; }

        [DynamoDBProperty("Feature")]
        public Feature? Feature { get; set; }

        // Required Date fields, generated by the system
        [DynamoDBProperty("DateListed")]
        public required DateOnly DateListed { get; set; }

        [DynamoDBProperty("LastUpdate")]
        public required DateTime LastUpdate { get; set; }
    }
}