using Amazon.DynamoDBv2.DataModel;

namespace PropertyHubLibrary.Models
{
    [DynamoDBTable("Property")]
    public class Property
    {
        // Partition Key, official MLS number
        [DynamoDBHashKey]
        public required string MLS { get; set; }

        // Mandatory fields in regular property listing
        public required string Type { get; set; }
        public required decimal Price { get; set; }
        public required int Bedrooms { get; set; }
        public required int Bathrooms { get; set; }
        public required int Parkings { get; set; }
        public required int Size { get; set; }
        public required int YearBuilt { get; set; }
        public required decimal Tax { get; set; }
        public required Address Address { get; set; }
        public required string Status { get; set; }
        public required string Description { get; set; }

        // Store only necessary information for agent
        public required string AgentRegistrationNumber { get; set; }

        // Optional fields
        public List<string> ImageUrls { get; set; } = new();
        public Feature? Feature { get; set; }

        // Required Date fields, generated by the system
        public required DateTime DateListed { get; set; }
        public required DateTime LastUpdate { get; set; }
    }
}